executable    = submitAssociator_2.sh
arguments     = $(ClusterID) $(ProcId)
output        = /afs/cern.ch/work/c/cbernkop/condor_output/condor_logs_932/output/hello.$(ClusterId).$(ProcId).out
error         = /afs/cern.ch/work/c/cbernkop/condor_output/condor_logs_932/error/hello.$(ClusterId).$(ProcId).err
log           = /afs/cern.ch/work/c/cbernkop/condor_output/condor_logs_932/log/hello.$(ClusterId).log
+JobFlavour   = "nextweek"
queue

